config/routes.rb
Rails.application.routes.draw do
  resources :fields
  resources :categories
  resources :sub_categories

  resources :categories do
    resources :sub_categories
  end

  resources :sub_categories do
    resources :fields
  end

  get "sub_categories/:id/gform", to: 'sub_categories#gform', as: 'visualize_form'  
  root "categories#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :sub_categories
  before_create :generate_slug
  before_update :generate_slug
  
  def generate_slug
    self.slug = name.parameterize
  end
  def to_param
    slug
  end

  #accepts_nested_attributes_for :sub_categories, allow_destroy: true
  #attr_accessible :name, :slug
end

app/models/field.rb
class Field < ActiveRecord::Base
  belongs_to :sub_category

  def self.tipos
    ['check_box', "text_field", 'text_area', "selection"]
  end

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  belongs_to :category
  has_many :fields
  before_create :generate_slug
  before_update :generate_slug

  def generate_slug
    self.slug = name.parameterize
  end

  def to_param
    slug
  end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

before_action :set_category, only: [:show, :edit, :update, :destroy, :index]

  def index
    @categories = Category.all
  end

  def show
    @categories = Category.find_by_slug(params[:id])
  end

  def new
    @category = Category.new
    render :new
  end

  def edit
    render :edit
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category, notice: 'Categoria criada com sucesso!'
    else
      render :new
    end
  end

  def update
    if @category.update(category_params)
      redirect_to @category, notice: 'Categoria foi atualizada com sucesso!'
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to sub_categories_url, notice: 'Campo excluido com sucesso.'
  end

  private

    def set_category
      @category = Category.find_by_slug(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :slug)
    end	

end

app/controllers/fields_controller.rb
class FieldsController < ApplicationController

  before_action :set_field, only: [:show, :edit, :update, :destroy]

  def index
    @fields = Field.all
  end

  def show
    @fields = Field.find(params[:id])
  end

  def new
    @field = Field.new
    @sub_category = SubCategory.find(params[:sub_category])
    render :new 
  end

  def edit
    render :edit
  end

  def create
    @field = Field.new(field_params)
    if @field.save
      redirect_to @field, notice: 'Campo criado com sucesso.'
    else
      render :new
    end
  end

  def update
    if @field.update(field_params)
      redirect_to @field, notice: 'Campo foi atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @field.destroy
    redirect_to :back, notice: 'Campo excluído com sucesso.'
  end

  private

    def set_field
      @field = Field.find(params[:id])
    end

    def field_params
      params.require(:field).permit(:order, :title, :tipo, :values, :sub_category_id)
    end


end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController

  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]

  def index
    @sub_categories = SubCategory.all
  end

  def new
	@sub_category = SubCategory.new
	@category = Category.find(params[:category])
	render :new
  end

  def show
  	@sub_categories = SubCategory.find_by_slug(params[:id])
    @field = Field.all
  end

  def gform
    @sub_categories = SubCategory.find_by_slug(params[:id])
    @field = Field.all
    render :gform 
  end
    

  def edit
    render :edit
  end

  def update
	  if @sub_category.update(sub_category_params)
		  flash[:notice] = "Sub-categoria atualizada com sucesso"
		  redirect_to @sub_category, notice: "Sub-categoria atualizada com sucesso"
	  else
		  render :edit
	  end
  end	

  def create
	  @sub_category = SubCategory.new sub_category_params
	  if @sub_category.save
		   flash[:notice] = "Produto salvo com sucesso"
		  redirect_to @sub_category, notice: 'Sub-categoria criada com sucesso!'
	  else
		  render :new
	  end
  end	

  def destroy
	  @sub_category.destroy
	  redirect_to sub_categories_url, notice: 'Categoria excluida com sucesso!'
  end

  private

  def set_sub_category
	  @sub_category = SubCategory.find_by_slug(params[:id])
  end

  def sub_category_params
	params.require(:sub_category).permit(:name,:slug,:category_id)
  end	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/fields_helper.rb
module FieldsHelper
end

app/helpers/sub_category_helper.rb
module SubCategoryHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this field from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Home', root_url %> |
<%= link_to 'Show', @category %> |
<%= link_to 'Back', :back %> 

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Categories</h1>

<table cellspacing="5">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>URL</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td><%= category.slug %></td>
        <td><%= link_to 'Show', category %></td> 
        <td><%= link_to 'Edit', edit_category_path(category) %></td> 
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render partial: 'form', locals: { novo: 'Criar a categoria'} %>

<%= link_to 'Home', root_url %> | |
<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @category.name %>
</p>

<p>
  <strong>URL:</strong>
  <%= @category.slug %>
</p>
<%= link_to 'Home', root_url %> |
<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', :back %> |
<%= link_to "Nova Sub-Categoria", new_sub_category_path(:category => @category.id) %> 
<br>
<table>
  <thead>
  <h4>Sub-Categorias</h4>
    <tr>
      <th>Id</th>
      <th>Nome</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
<% @categories.sub_categories.order(:id).each do |subcategory| %>
    <tr>
      <td><%= subcategory.id %></td>
      <td><%= subcategory.name %></td> 
      <td><%= link_to 'Show', subcategory %></td> 
      <td><%= link_to 'Destroy', subcategory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>  
   </tbody>
<% end %>    
</table>
<br>

app/views/fields/_form.html.erb
<%= form_for(@field) do |f| %>
  <% if @field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@field.errors.count, "error") %> prohibited this field from being saved:</h2>

      <ul>
      <% @field.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.select :tipo, Field.tipos %>
  </div>
  <div class="field">
    <%= f.label :values %><br>
    <%= f.text_area :values %>
  </div>
  <%= f.hidden_field :sub_category_id, :value => @sub_category.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fields/_formedit.html.erb
<%= form_for(@field) do |f| %>
  <% if @field.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@field.errors.count, "error") %> prohibited this field from being saved:</h2>

      <ul>
      <% @field.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order %><br>
    <%= f.number_field :order %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    <%= f.select :tipo, Field.tipos %>
  </div>
  <div class="field">
    <%= f.label :values %><br>
    <%= f.text_area :values %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fields/edit.html.erb
<h1>Editing Field</h1>

<%= render 'formedit' %>

<%= link_to 'Home', root_url %> |
<%= link_to 'Show', @field %> |
<%= link_to 'Back', fields_path %>

app/views/fields/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Fields</h1>

<table>
  <thead>
    <tr>
      <th>Sub-Categoria</th>
      <th>Order</th>
      <th>Title</th>
      <th>Type</th>
      <th>Values</th>
      <th colspan="8"></th>
    </tr>
  </thead>

  <tbody>
    <% @fields.each do |field| %>
      <tr>
        <td><%= field.sub_category_id %></td>
        <td><%= field.order %></td>
        <td><%= field.title %></td>
        <td><%= field.tipo %></td>
        <td><%= field.values %></td>
        <td><%= link_to 'Show', field %></td>
        <td><%= link_to 'Edit', edit_field_path(field) %></td>
        <td><%= link_to 'Destroy', field, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Home', root_url %> |
<%= link_to 'Back', :back %> 

app/views/fields/new.html.erb
<h1>New Field</h1>

<%= render partial: 'form', locals: { novo: 'Criar o campo'} %>

<%= link_to 'Home', root_url %> |
<%= link_to 'Back', :back %>

app/views/fields/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @field.order %>
</p>

<p>
  <strong>Title:</strong>
  <%= @field.title %>
</p>

<p>
  <strong>Type:</strong>
  <%= @field.tipo %>
</p>

<p>
  <strong>Values:</strong>
  <%= @field.values %>
</p>

<%= link_to 'Home', root_url %> |
<%= link_to 'Edit', edit_field_path(@field) %> |
<%= link_to 'Back', sub_categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Form</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sub_categories/_form.html.erb
<%= form_for(@sub_category) do |f| %>
  <% if @sub_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h2>

      <ul>
      <% @sub_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
  <%= f.hidden_field :category_id, :value => @category.id %>
  <%= f.submit %>
  </div>
<% end %>

app/views/sub_categories/_formedit.html.erb
<%= form_for(@sub_category) do |f| %>
  <% if @sub_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sub_category.errors.count, "error") %> prohibited this sub_category from being saved:</h2>

      <ul>
      <% @sub_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :name %>
  </div>
  <%= f.submit %>
<% end %>

app/views/sub_categories/edit.html.erb
<h1>Editing Sub Category</h1>

<%= render 'formedit' %>

<%= link_to 'Home', root_url %> |
<%= link_to 'Show', @sub_category %> |
<%= link_to 'Back', :back %>

app/views/sub_categories/gform.html.erb
<h1>Gerador de Form</h1>
      <% @sub_categories.fields.order(:order).each do |campo| %>
        
          <%= form_for Field.new do |f| %>
          <%= titulo = campo.title %>
          <br>
          <% case campo.tipo %>
          <% when "text_area" %>
           <%= f.text_area :order %>
          <% when "check_box" %>
            <%= f.check_box :order %>  
          <% when "text_field" %>
            <%= f.text_field :order %>
          <% when "selection" %>
            <% campo.values %>
            <%= f.select :order, campo.values.tr(",-"," ").split(' ') %>
          <% when "text_field" %>
            <%= f.text_field :order %>
          <% end %>
          <% end %> 
        
      <% end %>

<br><br>
<%= link_to 'Home', root_url %> |
<%= link_to 'Show', @sub_category %> |
<%= link_to 'Back', :back %>

app/views/sub_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sub Categories</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Categoria</th>
      <th>Name</th>
      <th>URL</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <td><%= sub_category.id %></td>
        <td><%= sub_category.category_id %></td>
        <td><%= sub_category.name %></td>
        <td><%= sub_category.slug %></td>
        <td><%= link_to 'Show', sub_category %></td>
        <td><%= link_to 'Edit', edit_sub_category_path(sub_category) %></td>
        <td><%= link_to 'Destroy', sub_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Home', root_url %> |
<%= link_to 'Back', :back %> 

<!-- Nao faz sentido poder criar uma sub-categoria a partir do index, apenas dentro de uma categoria 
teremos esta opção -->
<%#= link_to 'New Sub category', new_sub_category_path %>

app/views/sub_categories/new.html.erb
<h1>New Sub Category</h1>

<%= render partial: 'form', locals: { novo: 'Criar a sub-categoria'} %>

<%= link_to 'Home', root_url %> |
<%= link_to 'Back', :back %>

app/views/sub_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @sub_category.name %>
</p>

<p>
  <strong>URL:</strong>
  <%= @sub_category.slug %>
</p>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Title</th>
      <th>Type</th>
      <th colspan="5"></th>
    </tr>
  </thead>
  <tbody>
    <% @sub_categories.fields.order(:order).each do |campo| %>
    <tr>
      <td><%= campo.order %></td>
      <td><%= campo.tipo %></td>
      <td><%= campo.title %></td>
      <td><%= link_to 'Show', campo %></td>
      <td><%= link_to 'Destroy', campo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>  
	<% end %>
<%= link_to 'Home', root_url %> |
<%= link_to 'Edit', edit_sub_category_path %> |
<%= link_to "Novo campo", new_field_path(:sub_category => @sub_category.id) %> |
<%= link_to "Monta form", visualize_form_path %> |
<%= link_to 'Back', sub_categories_path %>
<br>